server:
  port: 9001
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm_saas?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    #    redis服务器地址
    host: 127.0.0.1
    #    redis服务器端口
    port: 6379
    #    redis数据库索引
    database: 0
    jedis:
      pool:
        #     连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #     连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #     连接池中的最大空闲连接
        max-idle: 8
        #     连接池中的最小空闲连接
        min-idle: 0
    #    连接超时时间（毫秒）
    timeout: 0
